//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SimpleManagerContact.portal.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Para confirmar o seu email e ativar a conta, clique no link abaixo:.
        /// </summary>
        public static string Email_ActivateAccount_Body {
            get {
                return ResourceManager.GetString("Email_ActivateAccount_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Esqueceu a sua senha? Não tem problema. Crie uma nova senha clicando no botão abaixo:.
        /// </summary>
        public static string Email_ActivateNewPassord_Body {
            get {
                return ResourceManager.GetString("Email_ActivateNewPassord_Body", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Se o botão não funcionar, copie e cole o seguinte link em seu navegador:.
        /// </summary>
        public static string Email_InvalidLinkMessage {
            get {
                return ResourceManager.GetString("Email_InvalidLinkMessage", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CNPJ é inválido!.
        /// </summary>
        public static string Error_Company_LegalID_Invalid {
            get {
                return ResourceManager.GetString("Error_Company_LegalID_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CNPJ é obrigatório!.
        /// </summary>
        public static string Error_Company_LegalID_Required {
            get {
                return ResourceManager.GetString("Error_Company_LegalID_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome da Empresa é obrigatório!.
        /// </summary>
        public static string Error_CompanyName_Required {
            get {
                return ResourceManager.GetString("Error_CompanyName_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email não é válido!.
        /// </summary>
        public static string Error_Email_Invalid {
            get {
                return ResourceManager.GetString("Error_Email_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to O email não é igual!.
        /// </summary>
        public static string Error_Email_Match {
            get {
                return ResourceManager.GetString("Error_Email_Match", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email é obrigatório!.
        /// </summary>
        public static string Error_Email_Required {
            get {
                return ResourceManager.GetString("Error_Email_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome é obrigatório!.
        /// </summary>
        public static string Error_FirstName_Required {
            get {
                return ResourceManager.GetString("Error_FirstName_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sobrenome é obrigatório!.
        /// </summary>
        public static string Error_LastName_Required {
            get {
                return ResourceManager.GetString("Error_LastName_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A senha deve conter caracteres maiusculos, minusculos e alfanuméricos..
        /// </summary>
        public static string Error_Password_Invalid {
            get {
                return ResourceManager.GetString("Error_Password_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter no mínimo 8 caracteres!.
        /// </summary>
        public static string Error_Password_Length {
            get {
                return ResourceManager.GetString("Error_Password_Length", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A senha não é igual!.
        /// </summary>
        public static string Error_Password_Match {
            get {
                return ResourceManager.GetString("Error_Password_Match", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha é obrigatória!.
        /// </summary>
        public static string Error_Password_Required {
            get {
                return ResourceManager.GetString("Error_Password_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Por favor, confirme os termos de uso!.
        /// </summary>
        public static string Error_Terms_Required {
            get {
                return ResourceManager.GetString("Error_Terms_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPF inválido!.
        /// </summary>
        public static string Error_User_LegalID_Invalid {
            get {
                return ResourceManager.GetString("Error_User_LegalID_Invalid", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPF é obrigatório!.
        /// </summary>
        public static string Error_User_LegalID_Required {
            get {
                return ResourceManager.GetString("Error_User_LegalID_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário é obrigatório!.
        /// </summary>
        public static string Error_Username_Required {
            get {
                return ResourceManager.GetString("Error_Username_Required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário/Senha Incorretos!.
        /// </summary>
        public static string Error_Wrong_UserPwd {
            get {
                return ResourceManager.GetString("Error_Wrong_UserPwd", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não foi localizado o token de identificação..
        /// </summary>
        public static string Exception_Http_Forbidden {
            get {
                return ResourceManager.GetString("Exception_Http_Forbidden", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Acesso não autorizado..
        /// </summary>
        public static string Exception_Http_Unauthorized {
            get {
                return ResourceManager.GetString("Exception_Http_Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Para confirmar o e-mail e ativar a conta clique no link enviado..
        /// </summary>
        public static string Label_ActivateAccount {
            get {
                return ResourceManager.GetString("Label_ActivateAccount", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Comprar.
        /// </summary>
        public static string Label_Buy {
            get {
                return ResourceManager.GetString("Label_Buy", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Um e-mail foi enviado para {0}..
        /// </summary>
        public static string Label_CheckEmail {
            get {
                return ResourceManager.GetString("Label_CheckEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CNPJ.
        /// </summary>
        public static string Label_Company_LegalID {
            get {
                return ResourceManager.GetString("Label_Company_LegalID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome da Empresa.
        /// </summary>
        public static string Label_CompanyName {
            get {
                return ResourceManager.GetString("Label_CompanyName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Não Aprovado.
        /// </summary>
        public static string Label_Denied {
            get {
                return ResourceManager.GetString("Label_Denied", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmação do Email.
        /// </summary>
        public static string Label_Email_Confirmation {
            get {
                return ResourceManager.GetString("Label_Email_Confirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nome.
        /// </summary>
        public static string Label_FirstName {
            get {
                return ResourceManager.GetString("Label_FirstName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enviar Convite.
        /// </summary>
        public static string Label_Invite {
            get {
                return ResourceManager.GetString("Label_Invite", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sobrenome.
        /// </summary>
        public static string Label_LastName {
            get {
                return ResourceManager.GetString("Label_LastName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ativar.
        /// </summary>
        public static string Label_Link_Activate {
            get {
                return ResourceManager.GetString("Label_Link_Activate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Entrar.
        /// </summary>
        public static string Label_Logar {
            get {
                return ResourceManager.GetString("Label_Logar", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Para confirmar o e-mail e ativar a conta clique no link enviado..
        /// </summary>
        public static string Label_NewPassord {
            get {
                return ResourceManager.GetString("Label_NewPassord", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Confirmação da Senha.
        /// </summary>
        public static string Label_Password_Confirmation {
            get {
                return ResourceManager.GetString("Label_Password_Confirmation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Declaro que li e aceito os termos e condições de uso do portal..
        /// </summary>
        public static string Label_TermsAndConditions {
            get {
                return ResourceManager.GetString("Label_TermsAndConditions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to CPF.
        /// </summary>
        public static string Label_User_LegalID {
            get {
                return ResourceManager.GetString("Label_User_LegalID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Usuário.
        /// </summary>
        public static string Label_UserName {
            get {
                return ResourceManager.GetString("Label_UserName", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Aguardando Aprovação!.
        /// </summary>
        public static string Label_Wait_Approval {
            get {
                return ResourceManager.GetString("Label_Wait_Approval", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Pt-Br.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Portal Klimb2b.
        /// </summary>
        public static string Main_Title {
            get {
                return ResourceManager.GetString("Main_Title", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 99.999.999/9999-99.
        /// </summary>
        public static string Mask_Company_LegalID {
            get {
                return ResourceManager.GetString("Mask_Company_LegalID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to 999.999.999-99.
        /// </summary>
        public static string Mask_User_LegalID {
            get {
                return ResourceManager.GetString("Mask_User_LegalID", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registrar nova loja.
        /// </summary>
        public static string Register_New {
            get {
                return ResourceManager.GetString("Register_New", resourceCulture);
            }
        }
    }
}
